version: '3.8'
services:
  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: urlshortener-api
    ports:
      - "5000:80"
    depends_on:
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - App__BaseUrl=http://localhost:5000

  ui:
    build:
      context: ./UrlShortener.UI
    container_name: urlshortener-ui
    ports:
      - "5002:80"
    depends_on:
      - api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  redisdata:
