apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlshortener-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: urlshortener-api
  template:
    metadata:
      labels:
        app: urlshortener-api
    spec:
      containers:
        - name: urlshortener-api
          image: urlshortener-api:dev
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"