apiVersion: v1
kind: Service
metadata:
  name: urlshortener-ui-service
spec:
  selector:
    app: urlshortener-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002
  type: NodePort