apiVersion: v1
kind: Service
metadata:
  name: urlshortener-api-service
spec:
  selector:
    app: urlshortener-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort